# references
#
# https://alacritty.org/config-alacritty.html
# https://sunnnychan.github.io/cheatsheet/linux/config/alacritty.yml.html
import = [
  # uncomment the color scheme: 
  "~/.config/alacritty/tokyonight_moon.toml",
]

live_config_reload = true

working_directory = "None"

[env]
TERM = "xterm-256color"

[window]
title = "Alacritty whjc"
dimensions = { columns = 140, lines = 80 }
padding = { x = 6, y = 6 }
opacity = 0.92
blur = false
# startup_mode = "Fullscreen"
decorations = "full"

[scrolling]
history = 10000

[font]
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }
bold = { family = "FiraMono Nerd Font Mono", style = "Bold" }
italic = { family = "FiraMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraMono Nerd Font Mono", style = "Bold Italic" }

size = 12.0
offset = { x = 1, y = 1 }
glyph_offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Block", blinking = "Never" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  # { key = "L", mods = "Control|Shift", chars = "l" },
]
