# Useful commands
# upgrade tools to latest `mise upgrade --bump`
[tools]
biome = "2.5.2"
fzf = "0.73.1"
lazygit = "0.63.0"
neovim = "0.12.4"
ruff = "0.15.20"
jq = "1.8.2"
yq = "4.53.3"
fd = "10.4.2"
direnv = "2.37.1"
stylua = "2.5.2"
lua-language-server = "3.18.2"
tmux = "3.7b"
ripgrep = "15.1.0"
node = "26"
"npm:@tailwindcss/language-server" = "latest"
"npm:yaml-language-server" = "latest"
go = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
golangci-lint = "latest"
gofumpt = "latest"
watchexec = "latest"
