# Useful commands
# upgrade tools to latest `mise upgrade --bump`
[tools]
biome = "2.4.11"
fzf = "0.71.0"
lazygit = "0.61.1"
neovim = "0.12.1"
ruff = "0.15.10"
jq = "1.8.1"
yq = "4.52.5"
fd = "10.4.2"
direnv = "2.37.1"
stylua = "2.4.1"
lua-language-server = "3.18.2"
tmux = "3.6a"
ripgrep = "15.1.0"
